apiVersion: cache.core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    app.kubernetes.io/name: contentconfiguration
    app.kubernetes.io/instance: contentconfiguration-sample
    app.kubernetes.io/part-of: extension-content-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: extension-content-operator
  name: contentconfiguration-sample
spec:
  # TODO(user): Add fields here
