apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: inline-json
  namespace: default
spec:
  inlineConfiguration:
    content: |
      {
      		"iAmOptionalCustomFieldThatShouldBeStored": "iAmOptionalCustomValue",
      		"luigiConfigFragment": [
      			{
      				"data": {
      					"nodeDefaults": {
      						"entityType": "global",
      						"isolateView": true
      					},
      					"nodes": [
      						{
      							"entityType": "global",
      							"icon": "home",
      							"label": "Overview",
      							"pathSegment": "home"
      						}
      					],
      					"texts": [
      						{
      							"locale": "de",
      							"textDictionary": {
      								"hello": "Hallo"
      							}
      						}
      					]
      				}
      			}
      		],
      		"name": "overview"
      	}
    contentType: "json"