apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: inline-json
  namespace: default
spec:
  inlineConfiguration:
    content: |
      {
        "name": "overview",
        "luigiConfigFragment": [
          {
            "data": {
              "nodes": [
                {
                  "entityType": "global",
                  "pathSegment": "home",
                  "label": "Overview",
                  "icon": "home",
                  "hideFromNav": true,
                  "defineEntity": {
                    "id": "example"
                  },
                  "children": [
                    {
                      "pathSegment": "overview",
                      "label": "Overview",
                      "icon": "home",
                      "url": "https://fiddle.luigi-project.io/examples/microfrontends/multipurpose.html",
                      "context": {
                        "title": "Welcome to OpenMFP Portal",
                        "content": " "
                      }
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    contentType: "json"